# Generated by Django 5.2.8 on 2025-11-25 08:37

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cible', models.CharField(choices=[('Kokowa', 'Kokowa'), ('Agadez', 'Agadez'), ('Diffa', 'Diffa'), ('Dosso', 'Dosso'), ('Maradi', 'Maradi'), ('Niamey', 'Niamey'), ('Tahoua', 'Tahoua'), ('Tillaberi', 'Tillaberi'), ('Zinder', 'Zinder')], default='Kokowa', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monnaie', models.CharField(default='XOF', max_length=10)),
                ('pays', models.CharField(max_length=2)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('succeeded', 'Réussie'), ('failed', 'Échouée')], default='pending', max_length=15)),
                ('payment_provider_method', models.CharField(default='My Nita', max_length=50)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('pays', models.CharField(max_length=2)),
                ('anonymat', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('model_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lutteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Agadez', 'Agadez'), ('Diffa', 'Diffa'), ('Dosso', 'Dosso'), ('Maradi', 'Maradi'), ('Niamey', 'Niamey'), ('Tahoua', 'Tahoua'), ('Tillaberi', 'Tillaberi'), ('Zinder', 'Zinder')], default='Tahoua', max_length=18)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6)),
                ('toise', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('payload', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_hmac', models.CharField(max_length=128)),
                ('ip_masked', models.CharField(max_length=50)),
                ('user_agent', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=2, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kokowa.contribution')),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='donateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_kokowa.donateur'),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='ipaymoney', max_length=50)),
                ('provider_ref', models.CharField(max_length=100)),
                ('info_transaction', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('statut', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monnaie', models.CharField(max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kokowa.contribution')),
            ],
        ),
        migrations.CreateModel(
            name='Soutient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soutien', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('donateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_kokowa.donateur')),
                ('lutteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_kokowa.lutteur')),
            ],
        ),
    ]
