# Generated by Django 5.2.8 on 2025-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutient',
            name='donateur',
        ),
        migrations.AlterField(
            model_name='soutient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
