# Generated by Django 5.2.8 on 2025-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0002_remove_soutient_donateur_alter_soutient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutteur',
            name='total_soutiens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_provider_method',
            field=models.CharField(choices=[('MyNita', 'MyNita'), ('Amanata', 'Amanata'), ('Airtel Money', 'Airtel Money'), ('Flooz', 'Flooz'), ('ZamaniCash', 'ZamaniCash'), ('Visa/MasterCard', 'Visa/MasterCard'), ('Virement', 'Virement')], default='MyNita', max_length=50),
        ),
    ]
