# Generated by Django 5.2.8 on 2025-12-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0003_lutteur_total_soutiens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutient',
            name='soutien',
        ),
    ]
