# Generated by Django 5.2.8 on 2025-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0004_remove_soutient_soutien'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutteur',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos_lutteurs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soutient',
            name='raison',
            field=models.CharField(choices=[('Fairplay', 'Fairplay'), ('Charisme', 'Charisme'), ('Performence', 'Performence')], default='Fairplay', max_length=15),
        ),
    ]
