# Generated by Django 5.2.8 on 2025-12-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0005_lutteur_photo_soutient_raison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote1', models.PositiveIntegerField(default=0)),
                ('vote2', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('f1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finaliste1', to='app_kokowa.lutteur')),
                ('f2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finaliste2', to='app_kokowa.lutteur')),
            ],
        ),
    ]
