# Generated by Django 5.2.8 on 2025-12-10 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0006_finale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lutteur',
            name='en_lisse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='soutient',
            name='raison',
            field=models.CharField(choices=[('Fairplay', 'Fairplay'), ('Charisme', 'Charisme'), ('Performance', 'Performance')], default='Fairplay', max_length=15),
        ),
        migrations.CreateModel(
            name='Affrontement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote1', models.PositiveIntegerField(default=0)),
                ('vote2', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('etape', models.CharField(choices=[('Eliminatoire', 'Eliminatoire'), ('8eme', '8eme'), ('1/4', '1/4'), ('1/2', '1/2'), ('Finale', 'Finale')], default='Eliminatoire', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('l1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutteur1', to='app_kokowa.lutteur')),
                ('l2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutteur2', to='app_kokowa.lutteur')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('favoris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_kokowa.lutteur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Finale',
        ),
    ]
