# Generated by Django 5.2.8 on 2025-12-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0007_lutteur_en_lisse_alter_soutient_raison_affrontement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affrontement',
            name='status',
            field=models.CharField(choices=[('en cours', 'en cours'), ('termine', 'termine'), ('a_venir', 'a_venir')], default='a_venir', max_length=9),
        ),
        migrations.AddField(
            model_name='affrontement',
            name='vainqueur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vainqueur_affrontement', to='app_kokowa.lutteur'),
        ),
    ]
