# Generated by Django 5.2.8 on 2025-12-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kokowa', '0008_affrontement_status_affrontement_vainqueur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='region',
            field=models.CharField(choices=[('Agadez', 'Agadez'), ('Diffa', 'Diffa'), ('Dosso', 'Dosso'), ('Maradi', 'Maradi'), ('Niamey', 'Niamey'), ('Tahoua', 'Tahoua'), ('Tillaberi', 'Tillaberi'), ('Zinder', 'Zinder')], default='Tahoua', max_length=18),
        ),
        migrations.AlterField(
            model_name='lutteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_lutteurs/'),
        ),
        migrations.AlterField(
            model_name='lutteur',
            name='poids',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lutteur',
            name='toise',
            field=models.DecimalField(decimal_places=2, default='1.60', max_digits=6),
        ),
    ]
